### ISSUE TITLE
nvidia driver kills process because it takes too long to 'launch'

### ISSUE THREAD

**Issue by rfdzan** [hkohko/t5-llm-training#7]
```
Traceback (most recent call last):
  File "K:\python\abs_summarization\run_main.py", line 11, in <module>
    main("mt5-small", train_epoch=1, model_output="trained-mt5-ID-test")
  File "K:\python\abs_summarization\abs_summarization\main.py", line 72, in main
    training.start_training(
  File "K:\python\abs_summarization\abs_summarization\training.py", line 66, in start_training
    train(epoch, tokenizer, model, device, training_loader, optimizer, wandb_init)
  File "K:\python\abs_summarization\abs_summarization\training.py", line 52, in train
    loss.backward()
  File "C:\Users\rifdi\AppData\Local\pypoetry\Cache\virtualenvs\abs-summarization-n8zjwGXO-py3.11\Lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "C:\Users\rifdi\AppData\Local\pypoetry\Cache\virtualenvs\abs-summarization-n8zjwGXO-py3.11\Lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\rifdi\AppData\Local\pypoetry\Cache\virtualenvs\abs-summarization-n8zjwGXO-py3.11\Lib\site-packages\wandb\wandb_torch.py", line 266, in <lambda>
    handle = var.register_hook(lambda grad: _callback(grad, log_track))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rifdi\AppData\Local\pypoetry\Cache\virtualenvs\abs-summarization-n8zjwGXO-py3.11\Lib\site-packages\wandb\wandb_torch.py", line 264, in _callback
    self.log_tensor_stats(grad.data, name)
  File "C:\Users\rifdi\AppData\Local\pypoetry\Cache\virtualenvs\abs-summarization-n8zjwGXO-py3.11\Lib\site-packages\wandb\wandb_torch.py", line 217, in log_tensor_stats
    tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: the launch timed out and was terminated
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

[L52](https://github.com/hkohko/t5-llm-training/blob/dcae0fdb8d615f3f17f766e91ccc96e3fa598c83/abs_summarization/training.py#L52) on [id_dataset_wip](https://github.com/hkohko/t5-llm-training/tree/id_dataset_wip)

**Comment by rfdzan** [comment]
solutions tried:

- [x] Use torch 2.0.0+cu118 from `pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118`
- [x] add "CUDA_LAUNCH_BLOCKING=1"
- [x] add "CUDA_VISIBLE_DEVICES=3"

- [x] Use torch 2.0.0+cu117 from `pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117`
- [ ] add "CUDA_LAUNCH_BLOCKING=1"
- [ ] add "CUDA_VISIBLE_DEVICES=3"

**Comment by rfdzan** [comment]
possible problem is with the amount of training data. make it around 3k-5k
